# The Docker image for GnuPG 2.
#
# Useful to manage the encryption keys for the backups.

FROM tk.bakfile_duplicity
MAINTAINER jcbrinfo <jcbrinfo@users.noreply.github.com>

ENTRYPOINT ["/usr/bin/gpg"]
